copy DATAFILE2.DAT DATAFILE3.DAT
copy DATAFILE2.DAT DATAFILE4.DAT
copy DATAFILE2.DAT DATAFILE5.DAT
copy DATAFILE2.DAT DATAFILE6.DAT
copy DATAFILE2.DAT DATAFILE7.DAT
copy DATAFILE2.DAT DATAFILE8.DAT
copy DATAFILE2.DAT DATAFILE9.DAT
copy DATAFILE2.DAT DATAFILE10.DAT
